services:
  device-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./qubex_config:/app/qubex_config
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "51021:51021"
    restart: unless-stopped
