services:
  device-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./qubex_config:/app/qubex_config
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "50052:50052"
    restart: unless-stopped
