proto:
  max_workers: 2
  address: "[::]:51021"
device_info:
  device_id: "anemone"
  provider_id: "qiqb"
  type: "QPU"
  max_qubits: 4
  max_shots: 10000
simulator_mode: false
device_status: active
device_topology_json_path: config/device_topology.json
