proto:
  max_workers: 2
  address: "[::]:51021"

device_info:
  device_id: "qulacs"
  provider_id: "oqtopus"
  max_qubits: 3
  max_shots: 10000

# Backend configuration
backend: "qulacs" # Available options: "qulacs", "qubex"

# Common backend settings
device_status_path: config/device_status
device_topology_json_path: config/device_topology_sim.json
